---
# tasks file for nexus

- name: NEXUS | install Java 
  yum:
    name:
      - java-1.8.0-openjdk-devel
    state: present

- name: Add the user nexus
  user:
    name: nexus

- name : Get the nexus archive file
  unarchive:
    src: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /opt/
    remote_src: yes
    owner: nexus

- name: Configure Nexus to run as a service
  template: src=nexus.service.j2 dest=/etc/systemd/system/nexus.service

- name: Reload Daemon
  systemd:
    daemon_reload: yes

- name: Start Nexus
  systemd:
    state: started
    enabled: yes
    name: nexus


 
